
development:
  adapter: mysql2
  database: college_app_development
  username: root
  password: root
  #socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  database: college_app_development
  username: root
  password: 


# development:

#   adapter: postgresql
#   encoding: unicode
#   database: estore1
#   host: localhost
#   pool: 5
#   username: postgres
#   password: root


