# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a0ad354ebe530c888ef2b690a005844d206ddb234a0687a511bb0e8f027ad722ddecd48a1a9d4a2206fd1418a4a6d55ccb09ae01aff030bf732539a5266ad26

test:
  secret_key_base: 028b253179b913956ab2e14cdf67b3eda43d1e250c8e0d5352643c749dfd10cfcbc3d83f67a6d880a1862a8451474e63f2e5181390de3f15c3637fc41f30f398

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:  'fa6cb06758384d548b6ae6353f0364f761ddb962e75b2262df30f623aac37dd965fd86c4db549221fc6d4594df554b6a0c305ee5c63c7e6d67c74239fe5dd499'
